import { Button, Container, Typography } from '@material-ui/core';
import Head from 'next/head';
import styled from 'styled-components';
import theme from '../theme';

const MyButton = styled(Button)`
  color: ${theme.palette.primary.main};
`;

const Home = () => {
  return (
    <div>
      <Head>
        <title>📖 Dictionary 📖</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1 >
          oi
        </h1>
        <Container fixed>
          <Button fullWidth variant="contained" color="primary">
            <Typography variant="h1">
              oi
            </Typography>
          </Button>
        </Container>
      </main>
    </div>
  )
}

export default Home
